import { Code, Brain, Target, Book } from "lucide-react";

export const userData = {
  id: "user123",
  username: "CodeNinja_Pro",
  avatar: "🥷",
  title: "Quiz Master",
  bio: "Passionate coder and problem solver. Love learning new algorithms and competitive programming.",
  email: "codeninja@example.com",
  location: "San Francisco, CA",
  joinedDate: "Jan 2024",
  xp: 2450,
  level: 12,
  streak: 7,
  longestStreak: 21,
  rank: 47,
  totalBadges: 8,
  quizzesCompleted: 23,
  eventsParticipated: 5,
  unlockedBadges: [
    "streakStarter",
    "quizMaster",
    "perfectScore",
    "fastThinker",
  ],
};

export const skillsData = [
  {
    id: 1,
    name: "Coding",
    icon: Code,
    color: "from-blue-500 to-cyan-500",
    xp: 2450,
    maxXp: 3000,
    level: 12,
    streak: 7,
  },
  {
    id: 2,
    name: "Mathematics",
    icon: Brain,
    color: "from-purple-500 to-pink-500",
    xp: 1800,
    maxXp: 2500,
    level: 9,
    streak: 3,
  },
  {
    id: 3,
    name: "Puzzles",
    icon: Target,
    color: "from-orange-500 to-red-500",
    xp: 980,
    maxXp: 1500,
    level: 5,
    streak: 12,
  },
  {
    id: 4,
    name: "Trivia",
    icon: Book,
    color: "from-green-500 to-emerald-500",
    xp: 3200,
    maxXp: 4000,
    level: 15,
    streak: 5,
  },
];

export const moduleData = {
  1: {
    name: "Coding",
    topics: [
      {
        id: 1,
        name: "Variables & Data Types",
        level: "Beginner",
        completion: 100,
        locked: false,
        xp: 150,
        badge: "🏆",
      },
      {
        id: 2,
        name: "Control Flow",
        level: "Beginner",
        completion: 100,
        locked: false,
        xp: 200,
        badge: "⭐",
      },
      {
        id: 3,
        name: "Functions",
        level: "Intermediate",
        completion: 75,
        locked: false,
        xp: 250,
        badge: null,
      },
      {
        id: 4,
        name: "Arrays & Objects",
        level: "Intermediate",
        completion: 40,
        locked: false,
        xp: 300,
        badge: null,
      },
      {
        id: 5,
        name: "Algorithms",
        level: "Advanced",
        completion: 0,
        locked: true,
        xp: 500,
        badge: null,
      },
    ],
  },
};

export const quizData = {
  1: {
    questions: [
      {
        id: 1,
        q: "What is the correct syntax to declare a variable in JavaScript?",
        options: ["var x = 5", "variable x = 5", "x := 5", "int x = 5"],
        correct: 0,
      },
      {
        id: 2,
        q: "Which operator is used for strict equality?",
        options: ["==", "===", "=", "!="],
        correct: 1,
      },
      {
        id: 3,
        q: "What does DOM stand for?",
        options: [
          "Document Object Model",
          "Data Object Model",
          "Digital Object Management",
          "Document Oriented Model",
        ],
        correct: 0,
      },
    ],
    timeLimit: 180,
    xpReward: 150,
  },
};

export const BADGES = {
  streakStarter: {
    id: "streakStarter",
    name: "Streak Starter",
    icon: "🔥",
    description: "Practice for 3 days in a row",
    color: "from-orange-500 to-red-500",
  },
  quizMaster: {
    id: "quizMaster",
    name: "Quiz Master",
    icon: "🎓",
    description: "Complete 10 quizzes",
    color: "from-blue-500 to-cyan-500",
  },
  fastThinker: {
    id: "fastThinker",
    name: "Fast Thinker",
    icon: "⚡",
    description: "Average under 30s per question",
    color: "from-yellow-500 to-orange-500",
  },
  allRounder: {
    id: "allRounder",
    name: "All-Rounder",
    icon: "🌟",
    description: "Practice all skill categories",
    color: "from-purple-500 to-pink-500",
  },
  perfectScore: {
    id: "perfectScore",
    name: "Perfect Score",
    icon: "💯",
    description: "Get 100% on any quiz",
    color: "from-green-500 to-emerald-500",
  },
  nightOwl: {
    id: "nightOwl",
    name: "Night Owl",
    icon: "🦉",
    description: "Practice after midnight",
    color: "from-indigo-500 to-purple-500",
  },
  earlyBird: {
    id: "earlyBird",
    name: "Early Bird",
    icon: "🌅",
    description: "Practice before 6 AM",
    color: "from-pink-500 to-rose-500",
  },
  master: {
    id: "master",
    name: "Master",
    icon: "👑",
    description: "Reach level 20",
    color: "from-yellow-600 to-orange-600",
  },
};

export const leaderboardData = {
  global: [
    {
      id: 1,
      rank: 1,
      username: "CodeMaster_Pro",
      avatar: "👨‍💻",
      xp: 15420,
      level: 28,
      badges: 12,
      streak: 45,
      rankChange: 0,
      weeklyXP: 2100,
    },
    {
      id: 2,
      rank: 2,
      username: "AlgoQueen",
      avatar: "👩‍🔬",
      xp: 14890,
      level: 27,
      badges: 10,
      streak: 32,
      rankChange: 1,
      weeklyXP: 1950,
    },
    {
      id: 3,
      rank: 3,
      username: "DebugNinja",
      avatar: "🥷",
      xp: 13750,
      level: 25,
      badges: 9,
      streak: 28,
      rankChange: -1,
      weeklyXP: 1800,
    },
    {
      id: 4,
      rank: 4,
      username: "DataWizard",
      avatar: "🧙",
      xp: 12340,
      level: 23,
      badges: 8,
      streak: 21,
      rankChange: 2,
      weeklyXP: 1650,
    },
    {
      id: 5,
      rank: 5,
      username: "PyThornado",
      avatar: "🐍",
      xp: 11680,
      level: 22,
      badges: 7,
      streak: 19,
      rankChange: 0,
      weeklyXP: 1500,
    },
    {
      id: 6,
      rank: 6,
      username: "LogicSensei",
      avatar: "👨‍🏫",
      xp: 10920,
      level: 21,
      badges: 8,
      streak: 17,
      rankChange: -2,
      weeklyXP: 1400,
    },
    {
      id: 7,
      rank: 7,
      username: "BinaryBoss",
      avatar: "👔",
      xp: 9850,
      level: 19,
      badges: 6,
      streak: 15,
      rankChange: 1,
      weeklyXP: 1250,
    },
  ],
  friends: [
    {
      id: 1,
      rank: 1,
      username: "AlgoQueen",
      avatar: "👩‍🔬",
      xp: 14890,
      level: 27,
      badges: 10,
      streak: 32,
      rankChange: 0,
      weeklyXP: 1950,
    },
    {
      id: 2,
      rank: 2,
      username: "CodeNinja_Pro",
      avatar: "🥷",
      xp: 2450,
      level: 12,
      badges: 8,
      streak: 7,
      rankChange: 1,
      weeklyXP: 420,
    },
    {
      id: 3,
      rank: 3,
      username: "DataWizard",
      avatar: "🧙",
      xp: 12340,
      level: 23,
      badges: 8,
      streak: 21,
      rankChange: -1,
      weeklyXP: 1650,
    },
  ],
  event: [
    {
      id: 1,
      rank: 1,
      username: "SpeedCoder",
      avatar: "🚀",
      xp: 3200,
      level: 15,
      badges: 5,
      streak: 5,
      rankChange: 0,
      weeklyXP: 3200,
    },
    {
      id: 2,
      rank: 2,
      username: "FastAlgo",
      avatar: "💨",
      xp: 2890,
      level: 14,
      badges: 4,
      streak: 4,
      rankChange: 2,
      weeklyXP: 2890,
    },
    {
      id: 3,
      rank: 3,
      username: "CodeNinja_Pro",
      avatar: "🥷",
      xp: 2650,
      level: 13,
      badges: 3,
      streak: 4,
      rankChange: -1,
      weeklyXP: 2650,
    },
  ],
};

export const recentActivities = [
  {
    id: 1,
    type: "quiz",
    title: "JavaScript Fundamentals",
    result: "9/10",
    xp: 180,
    time: "2 hours ago",
    icon: "📝",
  },
  {
    id: 2,
    type: "challenge",
    title: "Algorithm Sprint",
    result: "Completed",
    xp: 250,
    time: "5 hours ago",
    icon: "🏃",
  },
  {
    id: 3,
    type: "event",
    title: "Weekly Code Battle",
    result: "Rank #23",
    xp: 320,
    time: "1 day ago",
    icon: "⚔️",
  },
  {
    id: 4,
    type: "quiz",
    title: "Data Structures Advanced",
    result: "10/10",
    xp: 200,
    time: "2 days ago",
    icon: "📝",
  },
  {
    id: 5,
    type: "badge",
    title: 'Earned "Fast Thinker"',
    result: "Unlocked",
    xp: 100,
    time: "3 days ago",
    icon: "🏆",
  },
];

export const xpGrowthData = [
  { date: "Oct 25", xp: 1950 },
  { date: "Oct 26", xp: 2100 },
  { date: "Oct 27", xp: 2200 },
  { date: "Oct 28", xp: 2350 },
  { date: "Oct 29", xp: 2400 },
  { date: "Oct 30", xp: 2550 },
  { date: "Oct 31", xp: 2700 },
  { date: "Nov 01", xp: 2850 },
];

export const skillDistributionData = [
  { name: "Coding", value: 45, color: "#3b82f6" },
  { name: "Math", value: 25, color: "#a855f7" },
  { name: "Puzzles", value: 15, color: "#f97316" },
  { name: "Trivia", value: 15, color: "#10b981" },
];

export const monthlyEventsData = [
  { month: "Jun", events: 2 },
  { month: "Jul", events: 4 },
  { month: "Aug", events: 3 },
  { month: "Sep", events: 5 },
  { month: "Oct", events: 7 },
  { month: "Nov", events: 4 },
];

export const performanceInsights = {
  predictedRank: "Top 50 by next week",
  consistencyScore: 85,
  nextLevelXP: 550,
  averageSessionTime: "45 min",
  strongestSkill: "Coding",
  improvementArea: "Math",
};

export const avatarEmojis = {
  ninja: "🥷",
  robot: "🤖",
  wizard: "🧙",
  scientist: "👨‍🔬",
  astronaut: "👨‍🚀",
  detective: "🕵️",
  superhero: "🦸",
  pirate: "🏴‍☠️",
};
